### ISSUE TITLE
Marathon should reject apps that use COMMAND health checks with Docker.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#2140]
The only exception to this is when a custom executor is also specified (uncommon).

The Docker containerizer does not launch tasks using the command executor by default.  Without a custom executor to handle the health check the framework will never hear back regarding health status.  This results in apps that get stuck in the "deploying" state (also visible via the UI).

This limitation should be mentioned in the docs about health checks, and possibly in the docs about using the Docker containerizer as well.

Inspiration (question from stack overflow): http://stackoverflow.com/questions/32276226/strange-behavior-when-using-marathon-health-check-with-the-command-protocol-and/32280738#32280738

Minimal example to reproduce:

_1. Working app with health check (without Docker):_

```json
{
  "id": "without-docker",
  "cmd": "sleep 60",
  "cpus": 0.1,
  "mem": 64.0,
  "healthChecks":[
    {
      "protocol": "COMMAND",
      "command": { "value": "echo 0" },
      "intervalSeconds": 5
    }
  ]
}
```

_2. Broken app with health check (with Docker):_

```json
{
  "id": "with-docker",
  "cmd": "sleep 60",
  "cpus": 0.1,
  "mem": 64.0,
  "container":{
    "type": "DOCKER",
    "docker":{
      "image": "python:3",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0
        }
      ]
    }
  },
  "healthChecks":[
    {
      "protocol": "COMMAND",
      "command": { "value": "echo 0" },
      "intervalSeconds": 5
    }
  ]
}
```

cc @joerg84

**Comment by EvanKrall** [comment]
Hmm... We're using command health checks with docker containerizer on 0.8.2 / mesos 0.22.1, and it seems to work just fine. It does execute outside the container, but we use a wrapper script to find the appropriate container and `docker exec` in it.

**Comment by sybrandy** [comment]
I'm seeing the same issue and it appears it may be a Mesos issue.  I was on 0.22.1 and it worked, but on a system with 0.23.0 it didn't work.  I just upgraded the 0.22.1 system to 0.23.0 and it fails as well.  There's no mention of the health check in the logs and I see nothing in the stdout or stderr for the container.  I'm going to dig some more, but I wanted to mention this in case it helps.

FYI, marathon is version 0.9.0.

**Comment by sybrandy** [comment]
Check this out: https://issues.apache.org/jira/browse/MESOS-3136

**Comment by Raffo** [comment]
I've been experiencing several issues with health checks and I wonder if they can be related to this. I get all my tasks killed when the health checks are on. I'm running mesos 0.23.0-1.0.ubuntu1404, marathon 0.9.1-1.0.397.ubuntu1404. The health checks I tested are pretty basic ones coming from here: https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by TeaBough** [comment]
I've tested with mesos 0.24.1 / marathon 0.10.1 and the problem is still here. My application state is `Deploying` and the health bar stays gray. If I look at the stdout of my container I can see this : 
```
Launching health check process: /tmp/mesos/slaves/20150929-110120-857647296-15050-6726-S0/frameworks/20150929-110120-857647296-15050-6726-0000/executors/rights.7b164edc-66a3-11e5-88cc-2e8ac2c4bff6/runs/d70c1fd6-daef-48af-8800-4ed47dae1094/mesos-health-check --executor=(1)@192.168.31.52:35115 --health_check_json={"command":{"shell":true,"value":"docker exec mesos-20150929-110120-857647296-15050-6726-S0.d70c1fd6-daef-48af-8800-4ed47dae1094 sh -c \" echo 0""},"consecutive_failures":3,"delay_seconds":0,"grace_period_seconds":300,"interval_seconds":5,"timeout_seconds":20} --task_id=rights.7b164edc-66a3-11e5-88cc-2e8ac2c4bff6
Health check process launched at pid: 21579
```

**Comment by suizman** [comment]
Same here i've update both mesos 0.24.1 and marathon 0.10.1 and i am unable to see any logs about mesos launching health checks.
Is there any special flag to pass to mesos to activate the COMMAND health checks?

**Comment by carlossg** [comment]
Same problem with mesos 0.24.1 and marathon 0.11.0, although in https://issues.apache.org/jira/browse/MESOS-3136 it is set as fixed in mesos 0.24.1

**Comment by TeaBough** [comment]
Still the same problem with mesos 0.25.0 and marathon 0.11.0, although in https://issues.apache.org/jira/browse/MESOS-3136 it is set as fixed in mesos 0.25.0

**Comment by hekaldama** [comment]
@EvanKrall what is your wrapper script? Is it like:

https://issues.apache.org/jira/browse/MESOS-3136?focusedCommentId=14946563&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14946563

at all?

**Comment by colekowalski** [comment]
There are now proposed patches to fix command health checks: https://issues.apache.org/jira/browse/MESOS-3738

I have just tested marathon 0.11.1 with Mesos 0.25.0 (with the patch from MESOS-3738) and can confirm that this fixed any issues with command health checks we were seeing in our environment.

**Comment by EvanKrall** [comment]
@hekaldama Yeah, it's essentially that one-liner.

We did add a feature that looks for and reuses existing exec resources on the container that match the one we're about to run, so that the container info doesn't grow without bound. (Run `docker exec` several times against a container and then `docker inspect` the container, and you'll see info about each exec. This triggered https://issues.apache.org/jira/browse/MESOS-3724 after a few days of healthchecking.)

**Comment by hekaldama** [comment]
@EvanKrall interesting. Is this reproducible outside of mesos with just running exec on a container locally? I cannot seem to reproduce locally.

**Comment by christianparpart** [comment]
seems like I am running into the same issue, too; I am having a jenkins-master spawned via Marathon and I want to use any kind of health check. I have to use host networking though, so I cannot use HTTP health check mode, as this one doesn't let me allow to explicitly specify the target port to talk to (correct me if I am wrong, please).

The command health check though seems to be stuck for no reason (cannot find a "real" error in the logs. Health check used is: "curl -f -X GET http://$HOST:8080/cc.xml" (I assume that $HOST is resolving to the target node the container was spawned on - I couldn't find proof it via the docs, though.

**Comment by alfredcs** [comment]
Smilier issue here with Mesos 0.26 and Marathon 0.14. No detail error log except following . The health check cmd used is  "command": { "value": "curl --connect-timeout 3 -f -X GET http://$HOST:4243/images/json" },assuming $HOST is one of the deployed mesos-slave nodes. 

Feb 01 18:45:32 mesos-m11.vms.crd.ge.com marathon[17529]: [2016-02-01 18:45:32,342] INFO Forwarding health result [Unhealthy(basic-busybox.afed8a7c-c913-11e5-b338-6a047fcd0730,2016-02-01T18:43:29.723Z,,2016-02-01T18:45:32.342Z)] to health check actor [Actor[akka://marathon/user/$R#-351294637]] (mesosphere.marathon.health.MarathonHealthCheckManager$$EnhancerByGuice$$119255c3:ForkJoinPool-2-worker-7)
Feb 01 18:45:32 mesos-m11.vms.crd.ge.com marathon[17529]: [2016-02-01 18:45:32,343] INFO Received health result for app [/basic-busybox] version [2016-02-01T18:43:29.723Z]: [Unhealthy(basic-busybox.afed8a7c-c913-11e5-b338-6a047fcd0730,2016-02-01T18:43:29.723Z,,2016-02-01T18:45:32.342Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-1301)

**Comment by EvanKrall** [comment]
@hekaldama I believe Docker has changed their exec api in newer versions so that the exec resources don't stick around - that may be why you can't reproduce.

**Comment by bapetc** [comment]
I have tried the minimal example on Mesos 0.25.0 with Marathon 0.13.0
The problem is still here

**Comment by darshandzend** [comment]
Looks like the behaviour has changed in mesos 0.27.0. Now the `COMMAND` executes **inside** the docker container. I don't see it documented anywhere.

**Comment by brentley** [comment]
I just ran in to this and confirm what @darshandzend mentions. Changing my healthcheck command to one structured to run from INSIDE the container works perfectly.

**Comment by bwhaley** [comment]
Yep, same as @brentley. Health check was failing until I set it to use localhost and my app's port rather than the container. Works now. Marathon v1.1.1, Mesos v0.28.0

**Comment by gkleiman** [comment]
Recent versions of Mesos start the health check command inside the Docker container, so this issue is no longer relevant.

**Comment by brouberol** [comment]
It seems I'm still running into this issue with mesos 0.28.1 and marathon 0.15.3. My app stays into the _Deploying_ state. Is anybody still getting this?
