### ISSUE TITLE
Marathon lost FrameworkId and tasks after crashing 

### ISSUE THREAD

**Issue by gomes** [mesosphere/marathon#2224]
Environment:
Marathon 0.10.1 (--ha mode with 3 instances)
Mesos 0.23 (3 instances running on the same hosts that Marathon is)
A lot of event subscribers (we are using Qubit Bamboo for service discovery)
About 120 apps and 400 tasks 

The first error was in instance 13 (current leader):
```log
[ERROR] [09/07/2015 01:31:35.640] [marathon-akka.actor.default-dispatcher-52] [ActorSystem(marathon)] Uncaught error from thread [marathon-akka.actor.default-dispatcher-52] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.StackOverflowError
        at scala.collection.MapLFike$FilteredKeys.iterator(MapLike.scala:232)
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
        ...
        at scala.collection.MapLike$FilteredKeys.iterator(MapLike.scala:232)
```
This happened together with mesos reconciliation.
Some logs more in the same instance:
```log
[2015-09-07 01:31:35,661] INFO Shutting down services (mesosphere.marathon.Main$:42)
        
[2015-09-07 01:31:35,708] INFO Shutdown triggered (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:167)
[2015-09-07 01:31:35,708] INFO Stopping driver (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:222)

[2015-09-07 01:31:35,804] INFO Driver future completed. Executing optional abdication command. (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:193)
[2015-09-07 01:31:35,811] INFO Cancelling timer (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:173)
[2015-09-07 01:31:35,813] INFO Defeated (Leader Interface) (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:233)
[2015-09-07 01:31:35,813] INFO Defeat leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:276)
[2015-09-07 01:31:35,813] INFO Now standing by. Closing existing handles and rejecting new. (mesosphere.marathon.event.http.HttpEventStreamActor:96)
[INFO] [09/07/2015 01:31:35.813] [marathon-akka.actor.default-dispatcher-62] [akka://marathon/user/MarathonScheduler/$a] Suspending scheduler actor

[2015-09-07 01:31:35,816] INFO Do not proxy to myself. Waiting for consistent leadership state. Are we leader?: false, leader: Some(10.13.12.13:8080) (mesosphere.marathon.api.LeaderProxyFilter$:130)
        
[2015-09-07 01:31:35,819] INFO Leadership info is consistent again! (mesosphere.marathon.api.LeaderProxyFilter$:99)
```

Now the log of the new elected leader:
```log
[2015-09-07 01:31:35,813] INFO Candidate /marathon3/leader/member_0000000174 is now leader of group: [member_0000000176, member_0000000174] (com.twitter.common.zookeeper.CandidateImpl:152)
[2015-09-07 01:31:35,846] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:242)
[2015-09-07 01:31:35,926] INFO Elect leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:290)
[2015-09-07 01:31:35,927] INFO Running driver (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:185)
[2015-09-07 01:31:35,926] INFO Migration successfully applied for version Version(0, 10, 0) (mesosphere.marathon.state.Migration:70)

[INFO] [09/07/2015 01:31:35.949] [marathon-akka.actor.default-dispatcher-64] [akka://marathon/user/MarathonScheduler/$a] Starting scheduler actor

[2015-09-07 01:31:35,949] INFO Became active. Accepting event streaming requests. (mesosphere.marathon.event.http.HttpEventStreamActor:101)

[INFO] [09/07/2015 01:31:35.977] [marathon-akka.actor.default-dispatcher-64] [akka://marathon/user/MarathonScheduler/$a] Scheduler actor ready

[2015-09-07 01:31:36,078] INFO Reset offerLeadership backoff (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:320)
[2015-09-07 01:31:36,097] INFO Registered as 20150902-231517-235670794-5050-13589-0000 to master '20150902-231517-235670794-5050-13589' (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$a7f5cf0a:55)

[INFO] [09/07/2015 01:31:36.106] [marathon-akka.actor.default-dispatcher-64] [akka://marathon/user/offerReviver] Received scheduler registration event
[INFO] [09/07/2015 01:31:36.106] [marathon-akka.actor.default-dispatcher-71] [akka://marathon/user/$b] POSTing to all endpoints.
[INFO] [09/07/2015 01:31:36.106] [marathon-akka.actor.default-dispatcher-64] [akka://marathon/user/offerReviver] => revive offers NOW, canceling any scheduled revives
```
Then I saw the two frameworks running together and obviously I did some work to shutdown all old tasks because Marathon don't recognize all of then. 

I'm suspecting of the event bus as the cause of the crash, but I think the bigger problem is that Marathon didn't recognize the oldest FrameworkId.

Let me know if you guys need some more information.

**Comment by aquamatthias** [comment]
Hey @gomes the StackOverflow error really sounds bad. Can we have the log file of that instance?

The second snippet looks correct: the leadership is abdicated and the instance is waiting for consistent leadership.

The third snippet shows, that only two instances are applying for leadership. 
The leader is Marathon version 0.10.0 - do you have different versions in your cluster?
From the logs provided I do not see the loss of FrameworkId. 
Can you elaborate on that? Thanks!

**Comment by gomes** [comment]
Hi @aquamatthias, my bad, we have 3 instances running Marathon 0.10.0, not 0.10.1
About the loss of FrameworkId, the previous was 20150817-153018-202116362-5050-21340-0000

```
[2015-09-03 03:36:20,009] INFO Candidate /marathon3/leader/member_0000000173 is now leader of group: [member_0000000174, member_0000000173] (com.twitter.common.zookeeper.CandidateImpl:152)
[2015-09-03 03:36:20,011] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:242)
[2015-09-03 03:36:20,099] INFO Migration successfully applied for version Version(0, 10, 0) (mesosphere.marathon.state.Migration:70)
[2015-09-03 03:36:20,099] INFO Elect leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:290)
[2015-09-03 03:36:20,100] INFO Running driver (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:185)
[2015-09-03 03:36:20,103] INFO Became active. Accepting event streaming requests. (mesosphere.marathon.event.http.HttpEventStreamActor:101)
[INFO] [09/03/2015 03:36:20.103] [marathon-akka.actor.default-dispatcher-5] [akka://marathon/user/MarathonScheduler/$a] Starting scheduler actor
[2015-09-03 03:36:20,105] INFO Reset offerLeadership backoff (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$2c1b9a:320)
[2015-09-03 03:36:20,132] INFO Registered as 20150817-153018-202116362-5050-21340-0000 to master '20150902-231517-235670794-5050-13589' (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$a7f5cf0a:55
)
```

**Comment by a-nldisr** [comment]
Hello, 
We can report the same issue. We have seen the java process die, with this as a result:

![image](https://cloud.githubusercontent.com/assets/1867776/10130683/cae30da0-65ca-11e5-909e-6dfa99906f2e.png)

Im working on getting the logs, since we have 2G binary log files on the test machines it is taking some time. So far i found this:

```
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # A fatal error has been detected by the Java Runtime Environment:
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #  Internal Error (safepoint.cpp:310), pid=1301, tid=139942606366464
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #  guarantee(PageArmed == 0) failed: invariant
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # JRE version: OpenJDK Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # Java VM: OpenJDK 64-Bit Server VM (25.25-b02 mixed mode linux-amd64 compressed oops)
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # An error report file with more information is saved as:
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # //hs_err_pid1301.log
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: # If you would like to submit a bug report, please visit:
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #   http://bugreport.sun.com/bugreport/crash.jsp
Sep 23 09:28:57 mf02.surfsara.nl marathon[1318]: #
Sep 23 09:28:58 mf02.surfsara.nl systemd[1]: marathon.service: main process exited, code=killed, status=6/ABRT
Sep 23 09:28:58 mf02.surfsara.nl systemd[1]: Unit marathon.service entered failed state.
Sep 23 09:28:58 mf02.surfsara.nl systemd[1]: marathon.service failed.
Sep 23 09:29:18 mf02.surfsara.nl marathon[26660]: run_jar
Sep 23 09:29:18 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:18,832] INFO Starting Marathon 0.10.0 (mesosphere.marathon.Main$:87)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,190] INFO Connecting to Zookeeper... (mesosphere.marathon.Main$:37)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,207] INFO Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,207] INFO Client environment:host.name=mf02.surfsara.nl (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,207] INFO Client environment:java.version=1.8.0_25 (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.25-4.b18.fc21.x86_64/jre (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:java.class.path=/usr/bin/marathon (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:java.library.path=/usr/local/lib:/usr/lib:/usr/lib64 (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:os.version=3.17.4-301.fc21.x86_64 (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,208] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,209] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,210] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper:100)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,210] INFO Initiating client connection, connectString=mm01.surfsara.nl:2181,mm02.surfsara.nl:2181,mm03.surfsara.nl:2181 sessionTimeout=30000 watcher=com.twitter.common.zookeeper.ZooKeeperClient$3@21d8bcbe (org.apache.zookeeper.ZooKeeper:438)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,288] INFO Opening socket connection to server 10.200.37.91/10.200.37.91:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:975)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,358] INFO Socket connection established to 10.200.37.91/10.200.37.91:2181, initiating session (org.apache.zookeeper.ClientCnxn:852)
Sep 23 09:29:20 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:20,407] INFO Session establishment complete on server 10.200.37.91/10.200.37.91:2181, sessionid = 0x14fb16ba2830109, negotiated timeout = 30000 (org.apache.zookeeper.ClientCnxn:1235)
Sep 23 09:29:21 mf02.surfsara.nl marathon[26674]: [INFO] [09/23/2015 09:29:21.804] [marathon-akka.actor.default-dispatcher-4] [akka://marathon/user/offerReviver] Starting up
Sep 23 09:29:21 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:21,832] INFO Initiating client connection, connectString=mm01.surfsara.nl:2181,mm02.surfsara.nl:2181,mm03.surfsara.nl:2181 sessionTimeout=1800000 watcher=com.twitter.zk.EventBroker@7ed9499e (org.apache.zookeeper.ZooKeeper:438)
Sep 23 09:29:21 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:21,839] INFO Opening socket connection to server 10.200.37.93/10.200.37.93:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:975)
Sep 23 09:29:21 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:21,842] INFO Socket connection established to 10.200.37.93/10.200.37.93:2181, initiating session (org.apache.zookeeper.ClientCnxn:852)
Sep 23 09:29:21 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:21,871] INFO Session establishment complete on server 10.200.37.93/10.200.37.93:2181, sessionid = 0x34f6ead413f071a, negotiated timeout = 40000 (org.apache.zookeeper.ClientCnxn:1235)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,336] INFO Registering in Zookeeper with hostPort:mf02.surfsara.nl:8080 (mesosphere.marathon.MarathonModule:257)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,539] INFO Now standing by. Closing existing handles and rejecting new. (mesosphere.marathon.event.http.HttpEventStreamActor:96)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,586] INFO Adding HTTP support. (mesosphere.marathon.MarathonApp$$anon$1:47)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,587] INFO No HTTPS support configured. (mesosphere.marathon.MarathonApp$$anon$1:50)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,604] INFO Starting up (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$a77b4e58:146)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,604] INFO Beginning run (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$a77b4e58:151)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,605] INFO Will offer leadership after 500 milliseconds backoff (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$a77b4e58:325)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,605] INFO jetty-8.y.z-SNAPSHOT (org.eclipse.jetty.server.Server:272)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,803] INFO Registering com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchAdapter as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:113)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,804] INFO Registering com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:113)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,805] INFO Registering mesosphere.marathon.api.MarathonExceptionMapper as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:113)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,805] INFO Registering mesosphere.marathon.api.v2.AppsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,805] INFO Registering mesosphere.marathon.api.v2.TasksResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,805] INFO Registering mesosphere.marathon.api.v2.EventSubscriptionsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,805] INFO Registering mesosphere.marathon.api.v2.QueueResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,806] INFO Registering mesosphere.marathon.api.v2.GroupsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,806] INFO Registering mesosphere.marathon.api.v2.InfoResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,806] INFO Registering mesosphere.marathon.api.v2.LeaderResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,806] INFO Registering mesosphere.marathon.api.v2.DeploymentsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,806] INFO Registering mesosphere.marathon.api.v2.ArtifactsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,807] INFO Registering mesosphere.marathon.api.v2.SchemaResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:116)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,807] INFO Registering mesosphere.chaos.validation.ConstraintViolationExceptionMapper as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:113)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,809] INFO Initiating Jersey application, version 'Jersey: 1.18.1 02/19/2014 03:28 AM' (com.sun.jersey.server.impl.application.WebApplicationImpl:815)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,882] INFO Binding com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchAdapter to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,912] INFO Binding mesosphere.marathon.api.MarathonExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,915] INFO Binding mesosphere.chaos.validation.ConstraintViolationExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,916] INFO Binding com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:22 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:22,933] INFO HV000001: Hibernate Validator 5.1.2.Final (org.hibernate.validator.internal.util.Version:27)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,127] INFO Using HA and therefore offering leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$a77b4e58:332)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,188] INFO Set group member ID to member_0000000081 (com.twitter.common.zookeeper.Group:426)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,199] INFO Candidate /marathon/leader/member_0000000081 waiting for the next leader election, current voting: [member_0000000081, member_0000000079, member_0000000080] (com.twitter.common.zookeeper.CandidateImpl:165)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,599] INFO Binding mesosphere.marathon.api.v2.AppsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,617] INFO Binding mesosphere.marathon.api.v2.TasksResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,620] INFO Binding mesosphere.marathon.api.v2.EventSubscriptionsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,624] INFO Binding mesosphere.marathon.api.v2.QueueResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,639] INFO Binding mesosphere.marathon.api.v2.GroupsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,642] INFO Binding mesosphere.marathon.api.v2.InfoResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,644] INFO Binding mesosphere.marathon.api.v2.LeaderResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,648] INFO Binding mesosphere.marathon.api.v2.DeploymentsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,661] INFO Binding mesosphere.marathon.api.v2.ArtifactsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,666] INFO Binding mesosphere.marathon.api.v2.SchemaResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Sep 23 09:29:23 mf02.surfsara.nl marathon[26674]: [2015-09-23 09:29:23,748] INFO Started SelectChannelConnector@0.0.0.0:8080 (org.eclipse.jetty.server.AbstractConnector:338)
Sep 23 09:30:59 mf02.surfsara.nl systemd-coredump[26630]: Process 1301 (java) of user 0 dumped core.
```

We are using: 
marathon-0.10.0-1.0.409.el7.x86_64
java-1.8.0-openjdk-headless-1.8.0.25-4.b18.fc21.x86_64
mesos-0.23.0-1.0.centos701406.x86_64
mesosphere-zookeeper-3.4.6-0.1.20141204175332.centos7.x86_64

Setup:
3 instances of marathon in ha on seperate vm's from the mesos masters
3 instances of mesos masters in vm's. 

What seems to be the pattern is that the java process dies for x reason, marathon respawns and registers with a new framework id.

**Comment by gomes** [comment]
Today I had the problem again, Marathon became unresponsive and I restarted the current leader and after that, the new leader registered with a new FrameworkId and started to deploy all apps

I'm now running Marathon 0.11.1

```
[2015-10-28 12:10:17,577] INFO Proxying request to GET http://10.13.12.13:8080/ from 10.13.12.12:8080 (mesosphere.marathon.api.JavaUrlConnectionRequestForwarder$:289)
[2015-10-28 12:10:17,579] INFO 172.17.0.14 - - [28/Oct/2015:14:10:17 +0000] "GET //localhost:8080/ HTTP/1.0" 502 172 "-" "Sensu-HTTP-Check (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$71dfd42d:14)
[2015-10-28 12:10:18,018] INFO Candidate /marathon3/leader/member_0000000288 is now leader of group: [member_0000000290, member_0000000288, member_0000000289] (com.twitter.common.zookeeper.CandidateImpl:152)
[2015-10-28 12:10:18,019] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$5e112585:244)
[2015-10-28 12:10:18,035] INFO Initiating client connection, connectString=10.13.12.12:2181,10.13.12.13:2181,10.13.12.14:2181 sessionTimeout=1800000 watcher=com.twitter.zk.EventBroker@3a19caf5 (org.apache.zookeeper.ZooKeeper:438)
[2015-10-28 12:10:18,048] INFO Opening socket connection to server 10.13.12.14/10.13.12.14:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:975)
[2015-10-28 12:10:18,049] INFO Socket connection established to 10.13.12.14/10.13.12.14:2181, initiating session (org.apache.zookeeper.ClientCnxn:852)
[2015-10-28 12:10:18,055] INFO Session establishment complete on server 10.13.12.14/10.13.12.14:2181, sessionid = 0x35000b7cb869613, negotiated timeout = 40000 (org.apache.zookeeper.ClientCnxn:1235)
[2015-10-28 12:10:18,240] INFO Migration successfully applied for version Version(0, 11, 1) (mesosphere.marathon.state.Migration:85)
[2015-10-28 12:10:18,252] INFO Elect leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$5e112585:295)
[2015-10-28 12:10:18,252] INFO Running driver (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$5e112585:187)
[INFO] [10/28/2015 12:10:18.252] [marathon-akka.actor.default-dispatcher-20] [akka://marathon/user/leaderShipCoordinator] All actors active:
* Actor[akka://marathon/user/killOverdueStagedTasks#-1501348468]
* Actor[akka://marathon/user/launchQueue#291125118]
* Actor[akka://marathon/user/offerMatcherLaunchTokens#1776320406]
* Actor[akka://marathon/user/offerMatcherManager#939201752]
* Actor[akka://marathon/user/rateLimiter#23200717]
* Actor[akka://marathon/user/reviveOffersWhenWanted#829503753]
[2015-10-28 12:10:18,259] INFO Became active. Accepting event streaming requests. (mesosphere.marathon.event.http.HttpEventStreamActor:101)
[INFO] [10/28/2015 12:10:18.259] [marathon-akka.actor.default-dispatcher-15] [akka://marathon/user/MarathonScheduler/$a] Starting scheduler actor
[2015-10-28 12:10:18,260] INFO Reset offerLeadership backoff (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$5e112585:327)
[INFO] [10/28/2015 12:10:18.266] [marathon-akka.actor.default-dispatcher-17] [akka://marathon/user/rateLimiter/1] started RateLimiterActor
[INFO] [10/28/2015 12:10:18.325] [marathon-akka.actor.default-dispatcher-17] [akka://marathon/user/MarathonScheduler/$a] Scheduler actor ready
[2015-10-28 12:10:18,562] INFO Registered as 20150909-124930-235670794-5050-4874-0000 to master '20150909-124930-235670794-5050-4874' (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$3afa924e:48)
```
Mesos Master log

```
I1028 12:10:18.516634  4929 master.cpp:1834] Registering framework 20150909-124930-235670794-5050-4874-0000 (marathon) at scheduler-e9aa02d9-48de-4ef1-af18-c9150b83517e@10.13.12.12:9001 with checkpointing enabled and capabilities [  ]
I1028 12:10:18.516988  4929 hierarchical.hpp:386] Added framework 20150909-124930-235670794-5050-4874-0000
I1028 12:10:18.549805  4934 master.cpp:4290] Sending 72 offers to framework 20150909-124930-235670794-5050-4874-0000 (marathon) at scheduler-e9aa02d9-48de-4ef1-af18-c9150b83517e@10.13.12.12:9001
```

**Comment by aquamatthias** [comment]
@gomes The general logic if a leader got elected: 
1) read the framework id
2) if there is no framework id, a new framework id is generated and stored.

If you run into the case, that a new framework id is created, we need to understand why the old one is not readable:

1) You say Marathon became unresponsive. what do you mean?
2) Is zookeeper healthy? Any information in the zk logs? Could it be a zookeeper related problem? 
3) There is one specifc case, where the framework id is deleted by Marathon: if mesos reports a driver error. In the logs of the previous leading master, do you see an error log statement with this message:
"Committing suicide!" ? Can you share the logs of the previous leading master ( the last couple of minutes should be enough)

There is currently no way to circumvent new registration. We could add that as command line property. What do you think?

**Comment by aquamatthias** [comment]
@a-nldisr the problem you see is a dying JVM. I can not say anything from the logs provided.
What does the hs_err file say?
The ulimit is high enough?
You also use a rather old jvm (1.8.0_25), latest is 1.8.0_65 - perhaps try to update. 
You say that the Marathon process fails for various reasons. Can you please share those reasons?

**Comment by kolloch** [comment]
The first crash looks like #2185. That was hopefully fixed in 0.11.

**Comment by echinthaka** [comment]
I'm running marathon `0.11.1-1.0.432.ubuntu1404` on Ubuntu 14.04 and I'm still experiencing the same issue as mentioned above. 

We are using:
Marathon: `0.11.1-1.0.432.ubuntu1404`
Mesos: `0.23.1-0.2.61.ubuntu1404`
JDK" `1.8.0_60`

**Comment by aquamatthias** [comment]
Hey @echinthaka Can we have the (complete) logs for the timeframe? Interesting would be:
- ZooKeeper logs
- Mesos master logs
- Marathon logs.

If you had a Mesos driver error, the default behavior in Marathon until 0.14 is to delete the frameworkId.
We changed that in Marathon 0.14: https://github.com/mesosphere/marathon/pull/2765

**Comment by gomes** [comment]
@aquamatthias I think we can close this issue, since Marathon changed a lot and I don't have this kind of issue anymore.

**Comment by aquamatthias** [comment]
Close it for now.
